### ISSUE TITLE
master 4.0.0 throws StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by SierraGolf** [simpligility/android-maven-plugin#407]
this happens when my integration test project tries generate the sources and stumbles across my app.apk which is provided. the artifact's file name is "classes", since it refers to the target folder.

stacktrace:

```
on project integration: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-SNAPSHOT:generate-sources failed: String index out of range: -1
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-generate-sources of goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-1-SNAPSHOT:generate-sources failed: String index out of range: -1
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1911)
    at com.jayway.maven.plugins.android.common.UnpackedLibHelper.getJarFileForApk(UnpackedLibHelper.java:159)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.extractApkClassesJar(GenerateSourcesMojo.java:505)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.extractLibraryDependencies(GenerateSourcesMojo.java:438)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:247)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
```

**Comment by misterbobdobalina** [comment]
I am also having this problem...

**Comment by misterbobdobalina** [comment]
I can do mvn install on morse-flash, but I can also not do mvn compile. Fails with above error. I came here because I have that error also in my other project.
