### ISSUE TITLE
java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder

### ISSUE THREAD

**Issue by mstevens83** [simpligility/android-maven-plugin#492]
Since upgrading from AMP 4.0.0-rc.1 to rc.2 (and still with rc.3) I get the following crash when calling mvn (even a simple "mvn clean") on the parent pom of the project which uses AMP. Strangely it does _not_ happen when I call mvn on the project itself.

```
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:166)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: org.apache.maven.shared.dependency.graph.internal.Maven31DependencyGraphBuilder cannot be cast to org.apache.maven.shared.dependency.graph.DependencyGraphBuilder
        at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:86)
        at com.jayway.maven.plugins.android.common.DependencyResolver.getProjectDependenciesFor(DependencyResolver.java:49)
        at com.jayway.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.afterProjectsRead(ClasspathModifierLifecycleParticipant.java:115)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:310)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

Simply changing back to AMP 4.0.0-rc.1 (instead of rc.2 or 3) fixes the problem.

**Comment by aminabs** [comment]
Just to confirm,
I've already had a similar issue, i.e., build failed when I launched the command:
'mvn clean install'
from a parent project (parent's pom.xml). However, every single module successfully built running the same mvn command as above. Finally, I found that I was using different versions of android-maven-plugin inside child modules pom.xml files.

**Comment by akpmp** [comment]
I have run sciknowmine project given error like:
[ERROR] Internal error: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.maven.lifecycle.mapping.LifecyclePhase -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.maven.lifecycle.mapping.LifecyclePhase
How to resolve it 
please help me

Thanks/Regard
