### ISSUE TITLE
aapt Result=138, Error when generating sources. com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateRForApkLibDependency(GenerateSourcesMojo.java:902)

### ISSUE THREAD

**Issue by skauss** [simpligility/android-maven-plugin#504]
Hi
I use android-maven-plugin version 3.9.0-rc.2, Two day before I was able to build the project.
But now it fail (many resource files has changed in the last day's)
Inside Eclipse I am able to compile and run my application but if I use maven it fails.
mvn clean install
I get the Error 

[DEBUG] Adding non-constant-id
[DEBUG] Adding assets folder : /Users/sks/myworkspace/26/AndroidApp/XXStaging/target/unpacked-libs/maA_XXRes/combined-assets
[DEBUG] /Users/sks/android/android-sdk_r21-macosx/build-tools/20.0.0/aapt ...
...
[INFO] /bin/sh: line 1: 20882 Bus error: 10           /Users/sks/android/android-sdk_r21-macosx/build-tools/20.0.0/aapt package ...
....
DEBUG] ANDROID-040-000: Executed command: Commandline = /bin/sh -c cd /Users/sks/myworkspace/26/AndroidApp/EventimAppStaging && /Users/sks/android/android-sdk_r21-macosx/build-tools/20.0.0/aapt package --non-constant-id -m ....
....
 Result = 138

[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: 
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateRForApkLibDependency(GenerateSourcesMojo.java:902)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateApkLibRs(GenerateSourcesMojo.java:805)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateCorrectRJavaForApklibDependencies(GenerateSourcesMojo.java:768)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:749)
    at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:278)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

Is there a way to isolate the problem and get more information which resource file has the problem ?
In GenerateSourcesMojo I have seen some debug lines like "getLog().debug( "
How to enable this log may be this helps.

Regards

Stephan

**Comment by mosabua** [comment]
Closing old issue as cleanup
