### ISSUE TITLE
MASTER failing on LintoMojoIntegrationTest and ZipalignMojoIntegrationTest

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#540]
These all passed when I built the configurable_unpacked-libs branch.
So I don;t understand how they are failing now but weren't then.

```
Tests run: 6, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 3.408 sec <<< FAILURE! - in com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegration
Test
testDefaultUnskippedLintConfig[target/maven-installation/apache-maven-3.2.3](com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest)  Time ela
psed: 0.712 sec  <<< FAILURE!
java.lang.AssertionError: [[ERROR] Error executing Maven.]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
        at com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest.testDefaultUnskippedLintConfig(LintMojoIntegrationTest.java:70)

testSkipConfig[target/maven-installation/apache-maven-3.2.3](com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest)  Time elapsed: 0.156 sec
 <<< FAILURE!
java.lang.AssertionError: [[ERROR] Error executing Maven.]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
        at com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest.testSkipConfig(LintMojoIntegrationTest.java:52)

testDefaultUnskippedLintConfig[3.2.3](com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest)  Time elapsed: 0.125 sec  <<< FAILURE!
java.lang.AssertionError: [[ERROR] Error executing Maven.]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
        at com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest.testDefaultUnskippedLintConfig(LintMojoIntegrationTest.java:70)

testSkipConfig[3.2.3](com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest)  Time elapsed: 0.124 sec  <<< FAILURE!
java.lang.AssertionError: [[ERROR] Error executing Maven.]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
        at com.jayway.maven.plugins.android.standalonemojos.LintMojoIntegrationTest.testSkipConfig(LintMojoIntegrationTest.java:52)

Running com.jayway.maven.plugins.android.standalonemojos.LintMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.jayway.maven.plugins.android.standalonemojos.LintMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.ManifestUpdateMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.jayway.maven.plugins.android.standalonemojos.ManifestUpdateMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.MonkeyMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.jayway.maven.plugins.android.standalonemojos.MonkeyMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.MonkeyRunnerMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.jayway.maven.plugins.android.standalonemojos.MonkeyRunnerMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.UIAutomatorMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.jayway.maven.plugins.android.standalonemojos.UIAutomatorMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.UnpackMojoLazyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.jayway.maven.plugins.android.standalonemojos.UnpackMojoLazyTest
Running com.jayway.maven.plugins.android.standalonemojos.UnpackMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.jayway.maven.plugins.android.standalonemojos.UnpackMojoTest
Running com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoIntegrationTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.941 sec <<< FAILURE! - in com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoIntegra
tionTest
skipOnNonAndroidProject[3.2.3](com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoIntegrationTest)  Time elapsed: 0.556 sec  <<< FAILURE!
java.lang.AssertionError: [[ERROR] Error executing Maven., [ERROR] com.google.inject.ProvisionException: Guice provision errors:, [ERROR] Caused by: Guice provi
sion errors:, [ERROR] Caused by: Type org.apache.maven.plugin.internal.DefaultMavenPluginManager not present, [ERROR] Caused by: org.apache.maven.plugin.interna
l.DefaultMavenPluginManager]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.takari.maven.testing.executor.MavenExecutionResult.assertErrorFreeLog(MavenExecutionResult.java:44)
        at com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoIntegrationTest.skipOnNonAndroidProject(ZipalignMojoIntegrationTest.java:56)

Running com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 sec - in com.jayway.maven.plugins.android.standalonemojos.ZipalignMojoTest

Results :

Failed tests:
  LintMojoIntegrationTest.testDefaultUnskippedLintConfig:70 [[ERROR] Error executing Maven.]
  LintMojoIntegrationTest.testSkipConfig:52 [[ERROR] Error executing Maven.]
  LintMojoIntegrationTest.testDefaultUnskippedLintConfig:70 [[ERROR] Error executing Maven.]
  LintMojoIntegrationTest.testSkipConfig:52 [[ERROR] Error executing Maven.]
  ZipalignMojoIntegrationTest.skipOnNonAndroidProject:56 [[ERROR] Error executing Maven., [ERROR] com.google.inject.ProvisionException: Guice provision errors:,
 [ERROR] Caused by: Guice provision errors:, [ERROR] Caused by: Type org.apache.maven.plugin.internal.DefaultMavenPluginManager not present, [ERROR] Caused by:
org.apache.maven.plugin.internal.DefaultMavenPluginManager]

Tests run: 68, Failures: 5, Errors: 0, Skipped: 10

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.947 s
[INFO] Finished at: 2014-12-14T22:26:52+10:00
[INFO] Final Memory: 76M/1489M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project android-maven-plugin: There are test failures.

[ERROR]
[ERROR] Please refer to d:\Source\3rdParty\maven-android-plugin\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
d:\Source\3rdParty\maven-android-plugin>
```

**Comment by mosabua** [comment]
Might want to check how it goes now.. been a few changes on this. But more are to come as well so ...

**Comment by mosabua** [comment]
Is this working for you again now?

**Comment by mosabua** [comment]
Closing. Everything works for me. Please open a new ticket and link to this if there is still a problem
