### ISSUE TITLE
Exception while generating main dex classes file

### ISSUE THREAD

**Issue by WonderCsabo** [simpligility/android-maven-plugin#556]
I am experienting with multidex, and it seems since #526 a-m-p can generate the main dex list automatically. However, maybe it has a bug, it get this error trace:

```
 --- android-maven-plugin:4.1.0-SNAPSHOT:dex (default-dex) @ android-annotation-mutildex-option ---
 Error: Expecting class path separator ';' before '\Android\android-sdk\build-tools\21.1.2\lib\shrinkedAndroid.jar' in argument number 8
 Exception in thread "main" java.lang.NullPointerException
  at com.android.multidex.MainDexListBuilder.<init>(MainDexListBuilder.java:97)
  at com.android.multidex.MainDexListBuilder.main(MainDexListBuilder.java:67)
```

I debugged a little bit, and these are these are the arguments passed to the `mainDexClasses` script:

```
[--output, D:\Csabi\Repo\mutildex-androidannotation\target\mainDexClasses.txt, "D:\Csabi\Repo\mutildex-androidannotation\target\unpacked-libs\cas_multidex_1.0.0\classes.jar;C:\Users\WonderCsabo\.m2\repository\org\androidannotations\androidannotations-api\3.1\androidannotations-api-3.1.jar;D:\Csabi\Repo\mutildex-androidannotation\target\classes"]
```

Since i have little experience about multidexing, i do not know where this problem is coming from. @psorobka @mosabua any tips?

**Comment by WonderCsabo** [comment]
It is seen from the paths i guess, but i am noting i use Windows.

**Comment by mosabua** [comment]
I am on OSX so I cant easily test this. I will port the multi example in as a IT test soon .. that will help. But for now I will release 4.1.0 anyway since the multiDex is an experimental feature.

**Comment by athkalia** [comment]
I am seeing something similar:

```
[INFO] --- android-maven-plugin:4.2.0:dex (default-dex) @ application ---
[INFO] Error: Expecting class path separator ';' before '\Android\android-sdk\build-tools\23.0.2\lib\shrinkedAndroid.jar' in argument number 8
[INFO] Invalid option
[INFO] Usage:
[INFO]
[INFO] Short version: Don't use this.
[INFO]
[INFO] Slightly longer version: This tool is used by mainDexClasses script to build
[INFO] the main dex list.
[INFO] Convert classes to Dex : C:\Users\sakis\Desktop\intelliJ projects\follower\application\target
[INFO]
[INFO] UNEXPECTED TOP-LEVEL ERROR:
[INFO] java.io.FileNotFoundException: C:\Users\sakis\Desktop\intelliJ projects\follower\application\target\mainDexClasses.txt (The system cannot find the file specified)
[INFO]  at java.io.FileInputStream.open0(Native Method)
[INFO]  at java.io.FileInputStream.open(FileInputStream.java:195)
[INFO]  at java.io.FileInputStream.<init>(FileInputStream.java:138)
[INFO]  at java.io.FileInputStream.<init>(FileInputStream.java:93)
[INFO]  at java.io.FileReader.<init>(FileReader.java:58)
[INFO]  at com.android.dx.command.dexer.Main.readPathsFromFile(Main.java:436)
[INFO]  at com.android.dx.command.dexer.Main.runMultiDex(Main.java:361)
[INFO]  at com.android.dx.command.dexer.Main.run(Main.java:275)
[INFO]  at com.android.dx.command.dexer.Main.main(Main.java:245)
[INFO]  at com.android.dx.command.Main.main(Main.java:106)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by sytolk** [comment]
On debian with the last version of android-maven-plugin. I try to generating mainDexClasses when multiDex flag set to true and mainDexList is null 
```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.1:dex (default-dex) on project taxi-android-open: Failed to execute mainDexClasses: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd '/home/stanimir/Stil-Projects/TaxiAndroidOpen' && '/home/stanimir/android-sdk-linux/build-tools/23.0.2/mainDexClasses' '--output' '/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/mainDexClasses.txt' '"/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/taxi-android-open_obfuscated.jar"', Result = 11 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.1:dex (default-dex) on project taxi-android-open: Failed to execute mainDexClasses
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute mainDexClasses
	at com.simpligility.maven.plugins.android.phase08preparepackage.DexMojo.generateMainDexClassesFile(DexMojo.java:647)
	at com.simpligility.maven.plugins.android.phase08preparepackage.DexMojo.runDex(DexMojo.java:576)
	at com.simpligility.maven.plugins.android.phase08preparepackage.DexMojo.execute(DexMojo.java:258)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 25 more
Caused by: com.simpligility.maven.plugins.android.ExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd '/home/stanimir/Stil-Projects/TaxiAndroidOpen' && '/home/stanimir/android-sdk-linux/build-tools/23.0.2/mainDexClasses' '--output' '/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/mainDexClasses.txt' '"/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/taxi-android-open_obfuscated.jar"', Result = 11
	at com.simpligility.maven.plugins.android.CommandExecutor$Factory$DefaultCommandExecutor.executeCommand(CommandExecutor.java:248)
	at com.simpligility.maven.plugins.android.phase08preparepackage.DexMojo.generateMainDexClassesFile(DexMojo.java:643)
```

**Comment by athkalia** [comment]
Note this issue: https://code.google.com/p/android/issues/detail?id=187721

**Comment by sytolk** [comment]
Yes unquote the jar library is fixing this thanks @athkalia 
```
/bin/sh -c cd '/home/stanimir/Stil-Projects/TaxiAndroidOpen' && '/home/stanimir/android-sdk-linux/build-tools/23.0.2/mainDexClasses' '--output' '/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/mainDexClasses.txt' '/home/stanimir/.m2/repository/org/androidannotations/androidannotations-api/3.3.2/androidannotations-api-3.3.2.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_recyclerview-v7_23.1.1/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cm_google-material-typeface_2.2.0.1/classes.jar:/home/stanimir/.m2/repository/com/taxi-bulgaria/rest/open-rest-client-a/1.0.5/open-rest-client-a-1.0.5.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/isalt_target-tooltip-library_1.3.11/classes.jar:/home/stanimir/.m2/repository/org/mapsforge/mapsforge-map-android/master-SNAPSHOT/mapsforge-map-android-master-SNAPSHOT.jar:/home/stanimir/.m2/repository/net/java/truelicense/truelicense-obfuscate/2.6.1/truelicense-obfuscate-2.6.1.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/ca_acra_4.7.0/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-plus_8.4.0/classes.jar:/home/stanimir/.m2/repository/org/springframework/android/spring-android-rest-template/2.0.0.M3/spring-android-rest-template-2.0.0.M3.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-measurement_8.4.0/classes.jar:/home/stanimir/.m2/repository/com/google/code/findbugs/annotations/3.0.0/annotations-3.0.0.jar:/home/stanimir/.m2/repository/com/android/support/support-annotations/22.2.0/support-annotations-22.2.0.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgn_paginglistview_1.3/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_multidex_1.0.1/classes.jar:/home/stanimir/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-basement_8.4.0/classes.jar:/home/stanimir/.m2/repository/org/springframework/android/spring-android-core/2.0.0.M3/spring-android-core-2.0.0.M3.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_appcompat-v7_23.1.1/classes.jar:/home/stanimir/.m2/repository/org/mapsforge/mapsforge-map-android-extras/master-SNAPSHOT/mapsforge-map-android-extras-master-SNAPSHOT.jar:/home/stanimir/.m2/repository/com/mobsandgeeks/android-saripaar/1.0.7-SNAPSHOT/android-saripaar-1.0.7-SNAPSHOT.jar:/home/stanimir/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_design_23.1.1/classes.jar:/home/stanimir/.m2/repository/com/jakewharton/disklrucache/2.0.2/disklrucache-2.0.2.jar:/home/stanimir/.m2/repository/org/apache/httpcomponents/httpclient-android/4.3.5.1/httpclient-android-4.3.5.1.jar:/home/stanimir/.m2/repository/org/mapsforge/mapsforge-map/master-SNAPSHOT/mapsforge-map-master-SNAPSHOT.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/ctm_mapsforge_0.6.0/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-location_8.4.0/classes.jar:/home/stanimir/.m2/repository/de/greenrobot/eventbus/2.4.1/eventbus-2.4.1.jar:/home/stanimir/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.3/jackson-core-2.6.3.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cm_iconics-core_2.5.5/classes.jar:/home/stanimir/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.3/jackson-databind-2.6.3.jar:/home/stanimir/.m2/repository/io/reactivex/rxjava/1.0.14/rxjava-1.0.14.jar:/home/stanimir/.m2/repository/org/mapsforge/mapsforge-map-reader/master-SNAPSHOT/mapsforge-map-reader-master-SNAPSHOT.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-gcm_8.4.0/classes.jar:/home/stanimir/.m2/repository/com/taxi-bulgaria/rest/open-rest-client/1.0.5/open-rest-client-1.0.5.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cg_floatingactionbutton_1.10.1/classes.jar:/home/stanimir/.m2/repository/com/taxi-bulgaria/common/common/1.0.1-SNAPSHOT/common-1.0.1-SNAPSHOT.jar:/home/stanimir/.m2/repository/com/parse/bolts/bolts-android/1.2.0/bolts-android-1.2.0.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cgag_play-services-base_8.4.0/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_support-v4_23.1.1/libs/internal_impl-23.1.1.jar:/home/stanimir/.m2/repository/org/mapsforge/mapsforge-core/master-SNAPSHOT/mapsforge-core-master-SNAPSHOT.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/pca_android-reactive-location_0.8/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/classes:/home/stanimir/.m2/repository/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar:/home/stanimir/.m2/repository/com/caverock/androidsvg/1.2.2-beta-1/androidsvg-1.2.2-beta-1.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cas_support-v4_23.1.1/classes.jar:/home/stanimir/Stil-Projects/TaxiAndroidOpen/target/unpacked-libs/cfa_facebook-android-sdk_4.5.0/classes.jar'
      You should check if you need to specify additional program jars.
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [open-rest-client-a-1.0.5.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [mapsforge-map-android-master-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [truelicense-obfuscate-2.6.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [spring-android-rest-template-2.0.0.M3.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [annotations-3.0.0.jar:META-INF/MANIFEST.MF])                                                            
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [support-annotations-22.2.0.jar:META-INF/MANIFEST.MF])                                                   
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])                                                                                                    
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])                                                                      
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [jackson-annotations-2.6.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [spring-android-core-2.0.0.M3.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/notice.txt] (Duplicate zip entry [spring-android-core-2.0.0.M3.jar:META-INF/notice.txt])
Warning: can't write resource [META-INF/license.txt] (Duplicate zip entry [spring-android-core-2.0.0.M3.jar:META-INF/license.txt])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [mapsforge-map-android-extras-master-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-saripaar-1.0.7-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [guava-18.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [disklrucache-2.0.2.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [httpclient-android-4.3.5.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [httpclient-android-4.3.5.1.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [mapsforge-map-master-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [eventbus-2.4.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [jackson-core-2.6.3.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [jackson-core-2.6.3.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/NOTICE] (Duplicate zip entry [jackson-core-2.6.3.jar:META-INF/NOTICE])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [jackson-databind-2.6.3.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/LICENSE] (Duplicate zip entry [jackson-databind-2.6.3.jar:META-INF/LICENSE])
Warning: can't write resource [META-INF/NOTICE] (Duplicate zip entry [jackson-databind-2.6.3.jar:META-INF/NOTICE])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [rxjava-1.0.14.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [mapsforge-map-reader-master-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [open-rest-client-1.0.5.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [common-1.0.1-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [bolts-android-1.2.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [internal_impl-23.1.1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [mapsforge-core-master-SNAPSHOT.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [kxml2-2.3.0.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [androidsvg-1.2.2-beta-1.jar:META-INF/MANIFEST.MF])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
Warning: can't write resource [dummy] (Duplicate zip entry [classes.jar:dummy])
```
