### ISSUE TITLE
IllegalStateException with Robolectric and android-maven-plugin 3.8.2 or higher.

### ISSUE THREAD

**Issue by kingargyle** [simpligility/android-maven-plugin#578]
After upgrading our build to use android-maven-plugin 4.1.0, about 200 of our tests started to fail with the following error that were working with the 3.7.0 version of the plugin. All of these tests were working with 3.7.0, and I know a large number of changes.  I saw a similiar issue on another forum where somebody was able to get things to work with 3.8.1, but it broke after that.  We can't use 3.8.1 because we need the AAR support.  

I've posted this issue on Robolectric's tracker as well.

I've checked our themes and they are extending from the appropriate Theme.AppCompat descendent.

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:151)
    at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:138)
    at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
    at com.altair.fusion.android.injection.InjectingFragmentActivity.onCreate(InjectingFragmentActivity.java:11)
    at com.altair.fusion.android.activities.FusionFragmentActivity.onCreate(FusionFragmentActivity.java:95)
    at com.altair.fusion.android.activities.student.AbstractStudentActivity.onCreate(AbstractStudentActivity.java:53)
    at com.altair.fusion.android.activities.student.StudentActivity.onCreate(StudentActivity.java:35)
    at android.app.Activity.performCreate(Activity.java:5133)
    at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
    at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
    at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
    at org.robolectric.util.ActivityController.create(ActivityController.java:111)
    at org.robolectric.util.ActivityController.create(ActivityController.java:122)
    at com.altair.fusion.android.activities.student.StudentActivityTest.restNavigationDrawerButtonStateEnablesMyWeekButtonWhenIntentIsMyClasses(StudentActivityTest.java:562)

**Comment by kingargyle** [comment]
The failures are occuring because the items are APKLibs.  If I change to use the AAR version of the dependencies, then things work as expected.  I know that APKLib support is listed as deprecated, but there are still a LOT of older libraries that are only available in APKLib format, and in many cases we don't have control over those libraries.   So it would be nice to get this fixed.

**Comment by mosabua** [comment]
I agree.. I towuld be nice. Might be hard to get sorted to be honest. @william-ferguson-au probably knows that part of the plugin best. Or @Shusshu .. but all of us are tied up a lot.

**Comment by william-ferguson-au** [comment]
It's very low on my priority queue. And that queue is loooooong

What libraries of any value still exist only as apklib?

**Comment by kingargyle** [comment]
ViewPagerIndicator is the one we use currently.   BadgerView is another one we use, but we ended up bringing that code.  Not everybody has switched to using IntelliJ and Android Studio, so there are still a lot of internal legacy APKLibs in enterprises that have been developed and still need to be used.  

With eclipse/andmore I do plan on getting AAR support going but that is still going to be a bit, and there are still cases where mixing apklib and aar needs to happen.

**Comment by Shusshu** [comment]
You can clone the project and build it yourself as an aar and deploy it to your company repository. That's what I used to do to get rid of ALL apklibs!

**Comment by kingargyle** [comment]
Yeah.  If the company you are working for lets you do it.  Unfortunately not an option in a lot of cases.  In many cases they just want to get the item from maven central.   Anyways, there are valid reasons why apklib and aars still need to exist.

**Comment by Shusshu** [comment]
You can even make a repository on github....  Apklib is gonna disappear but
aar will stay

**Comment by kingargyle** [comment]
Yes I understand it is going away.  In the mean time I guess for those projects that need APKLib I'll have to stick with 3.0 until the eclipse Andmore and the m2e-android project support the AAR format.

**Comment by mosabua** [comment]
Closing old issue since it wont be worked on at this stage anyway.
