### ISSUE TITLE
Error when generating sources. org.apache.maven.plugin.MojoExecutionException: AndroidManifest.xml file wasn't found in next place: 

### ISSUE THREAD

**Issue by danhantao** [simpligility/android-maven-plugin#607]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mingqihui-android 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mingqihui-android ---
[INFO] Deleting /Users/danhantao/dev/workspaces/retech/company-android/target
[INFO] 
[INFO] --- android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) @ mingqihui-android ---
[INFO] Extracting libs
[INFO] Extracting aar super-sdk...
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: AndroidManifest.xml file wasn't found in next place: /Users/danhantao/dev/workspaces/retech/company-android/target/unpacked-libs/cgcp_library
	at com.jayway.maven.plugins.android.AbstractAndroidMojo.extractPackageNameFromAndroidArtifact(AbstractAndroidMojo.java:1011)
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.getPackageCompareMap(GenerateSourcesMojo.java:838)
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.checkPackagesForDuplicates(GenerateSourcesMojo.java:693)
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.627 s
[INFO] Finished at: 2015-03-10T21:19:30+08:00
[INFO] Final Memory: 17M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:4.0.0-rc.2:generate-sources (default-generate-sources) on project mingqihui-android: AndroidManifest.xml file wasn't found in next place: /Users/danhantao/dev/workspaces/retech/company-android/target/unpacked-libs/cgcp_library -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by danhantao** [comment]
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T01:29:23+08:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"

i don't know why, try any ...

**Comment by william-ferguson-au** [comment]
I would start by upgrading to android-maven-plugin-4.1.1

**Comment by athkalia** [comment]
can you post your pom please ?

**Comment by mosabua** [comment]
We definitely had issues with this in the rc phase. You need to upgrade to the latest version for us to be able to help you. I will close assuming that it will work. Reopen if I am wrong ;-)

**Comment by danhantao** [comment]
ok,thank you,I have solved this problem. The problem is due to the aar file is packaged in 3.2, I used 3.9.0-rc2 repackage it.

**Comment by mosabua** [comment]
I would suggest to upgrade to 4.0.0 at least nevertheless.

**Comment by tchoulihan** [comment]
This is still an issue for me in version `4.3.0` . 

I've got my AndroidManifest.xml in the src/main/ folder, yet I still get the following error:
```
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.1.1:generate-sources (default-generate-sources) on project tt: AndroidManifest.xml file wasn't found in next place: /home/tyler/git/tt/target/unpacked-libs/cg_CastCompanionLibrary_0.0.1
```

The problem goes away when I remove this library from my dependencies:
```
<dependency>
			<groupId>com.google</groupId>
			<artifactId>CastCompanionLibrary</artifactId>
			<version>0.0.1</version>
			<scope>system</scope>
			<systemPath>${basedir}/src/main/libs/CastCompanionLibrary-debug.aar</systemPath>
			<type>aar</type>
		</dependency>
```

which unfortunately I need to use.

**Comment by william-ferguson-au** [comment]
@tchoulihan you are not using `4.3.0` as your error says, you are still using `4.1.1`
