### ISSUE TITLE
AndroidManifest.xml  - 2 issues, systempath dependency, and can't find res folder values

### ISSUE THREAD

**Issue by dessalines** [simpligility/android-maven-plugin#679]
The **first issue**, is that when I include this systemPath dependency:

``` xml
        <dependency>
            <groupId>com.google</groupId>
            <artifactId>CastCompanionLibrary</artifactId>
            <version>0.0.1</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/libs/CastCompanionLibrary-debug.aar</systemPath>
            <type>aar</type>
        </dependency>
```

I get the following _AndroidManifest.xml file wasn't found in next place_ error:

```
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: AndroidManifest.xml file wasn't found in next place: /home/tyler/git/tt/target/unpacked-libs/cg_CastCompanionLibrary_0.0.1
    at com.simpligility.maven.plugins.android.AbstractAndroidMojo.extractPackageNameFromAndroidArtifac
...
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.3.0:generate-sources (default-generate-sources) on project tt: AndroidManifest.xml file wasn't found in next place: /home/tyler/git/tt/target/unpacked-libs/cg_CastCompanionLibrary_0.0.1 -> [Help 1]
```

The **second issue** , is that when I remove that dependency, I get various *no resource found @drawable or @string \* errors, even though my folders are in the correct locations:

```
/src/main/AndroidManifest.xml
/src/main/res
/src/main/gen
```

the error:

```
[INFO] Generating R file for com.github.tchoulihan:tt:apk:0.0.1-SNAPSHOT
[INFO] /home/tyler/git/ttd/target/AndroidManifest.xml:27: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').
[INFO] 
[INFO] /home/tyler/git/tt/target/AndroidManifest.xml:27: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').
[INFO] 
[INFO] /home/tyler/git/tt/target/AndroidManifest.xml:27: error: Error: No resource found that matches the given name (at 'theme' with value '@style/UAmpAppTheme').
[INFO] 
[INFO] /home/tyler/git/tt/target/AndroidManifest.xml:29: error: Error: No resource found that matches the given name (at 'resource' with value '@xml/automotive_app_desc').
[INFO] 
[INFO] /home/tyler/git/tt/target/AndroidManifest.xml:33: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').
[INFO] 
[INFO] /home/tyler/git/tt/target/AndroidManifest.xml:47: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').
...
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: 
    at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:899)
    at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:328)
...

Caused by: com.simpligility.maven.plugins.android.ExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/tyler/git/tt && /home/tyler/android-sdks/build-tools/23.0.1/aapt package -m -J /home/tyler/git/tt/target/generated-sources/r -f --no-crunch -M /home/tyler/git/tt/target/AndroidManifest.xml -S /home/tyler/git/ttd/target/unpacked-libs/cas_appcompat-v7_23.0.1/res -S /home/tyler/git/ttd/target/unpacked-libs/cas_support-v4_23.0.1/res -S /home/tyler/git/ttd/target/unpacked-libs/cas_cardview-v7_22.0.0/res -S /home/tyler/git/ttd/target/unpacked-libs/cas_mediarouter-v7_22.0.0/res -S /home/tyler/git/ttd/target/unpacked-libs/cgas_library_5.0.0/res -S /home/tyler/git/ttd/target/unpacked-libs/ccm_library_0.0.2/res -S /home/tyler/git/ttd/target/unpacked-libs/cgag_play-services-cast_7.8.0/res -S /home/tyler/git/ttd/target/unpacked-libs/cgag_play-services-base_7.8.0/res --auto-add-overlay -A /home/tyler/git/ttd/target/generated-sources/combined-assets -I /home/tyler/android-sdks/platforms/android-23/android.jar --output-text-symbols /home/tyler/git/ttd/target, Result = 1
    at com.simpligility.maven.plugins.android.CommandExecutor$Factory$DefaultCommandExecutor.executeCommand(CommandExecutor.java:248)
    at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:895)
```

**Comment by tchoulihan** [comment]
Here's my pom for reference:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.github.tchoulihan</groupId>
	<artifactId>tt</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>apk</packaging>

	<properties>
		<!-- at test time this will be overridden with snapshot version -->
		<it-plugin.version>4.3.0</it-plugin.version>
	</properties>


	<repositories>
		<repository>
			<id>android-support</id>
			<name>android-support</name>
			<url>file://${env.ANDROID_HOME}/extras/android/m2repository</url>
		</repository>
		<repository>
			<id>project.local2</id>
			<name>LocalSdkGoogleRepository</name>
			<url>file:${env.ANDROID_HOME}/extras/google/m2repository</url>
		</repository>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>

	</repositories>



	<build>
		<sourceDirectory>src</sourceDirectory>
		<finalName>${project.artifactId}</finalName>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.simpligility.maven.plugins</groupId>

					<artifactId>android-maven-plugin</artifactId>
					<version>${it-plugin.version}</version>
					<extensions>true</extensions>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>com.simpligility.maven.plugins</groupId>

				<artifactId>android-maven-plugin</artifactId>
				<configuration>
					<includeLibsJarsFromAar>true</includeLibsJarsFromAar>
					<sdk>
						<platform>23</platform>
					</sdk>
					<androidManifestFile>
						${project.basedir}/src/main/AndroidManifest.xml
					</androidManifestFile>
					<resourceDirectory>${project.basedir}src/res</resourceDirectory>
					<manifest>
						<debuggable>true</debuggable>
					</manifest>

				</configuration>
				<extensions>true</extensions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.google.android</groupId>
			<artifactId>android</artifactId>
			<version>4.1.1.4</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>appcompat-v7</artifactId>
			<version>23.0.1</version>
			<type>aar</type>
		</dependency>


		<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>support-v4</artifactId>
			<version>23.0.1</version>
			<type>aar</type>
		</dependency>

		<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>cardview-v7</artifactId>
			<version>22.0.0</version>
			<type>aar</type>
		</dependency>

		<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>mediarouter-v7</artifactId>
			<version>22.0.0</version>
			<type>aar</type>
		</dependency>

		<dependency>
			<groupId>com.github.amlcurran.showcaseview</groupId>
			<artifactId>library</artifactId>
			<version>5.0.0</version>
			<type>aar</type>
		</dependency>

		<dependency>
			<groupId>com.chrisanderson.mediabrowsercompat</groupId>
			<artifactId>library</artifactId>
			<version>0.0.2</version>
			<type>aar</type>
			<exclusions>
				<exclusion>
					<groupId>com.android.support</groupId>
					<artifactId>support-v4</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.android.support</groupId>
					<artifactId>appcompat-v7</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.google.android.gms</groupId>
			<artifactId>play-services-cast</artifactId>
			<version>7.8.0</version>
			<type>aar</type>
		</dependency>

<!-- 		<dependency> -->
<!-- 			<groupId>com.google</groupId> -->
<!-- 			<artifactId>CastCompanionLibrary</artifactId> -->
<!-- 			<version>0.0.1</version> -->
<!-- 			<scope>system</scope> -->
<!-- 			<systemPath>${basedir}/src/main/libs/CastCompanionLibrary-debug.aar</systemPath> -->
<!-- 			<type>aar</type> -->
<!-- 		</dependency> -->




	</dependencies>
</project>
```

**Comment by tchoulihan** [comment]
I'd also like to note that the target directory seems to lack any R generated files, although i'm not sure which directory they're supposed to be in.

**Comment by mosabua** [comment]
System scoped dependencies are afaik NOT supported in the Android Maven Plugin. That was a conscious decision when we implemented the aar support from what I can remember. I might be wrong though. wdyt @simpligility/android-maven-plugins-core-committers  ?

**Comment by mosabua** [comment]
And in terms of the resources.. where are the located? In your source tree or are they coming from an aar ?

**Comment by tchoulihan** [comment]
Most of the dependencies are in the android repos: `<url>file://${env.ANDROID_HOME}/extras/android/m2repository</url>`, except for the one special library that requires a system path. That one is in one of the source folders.

**Comment by william-ferguson-au** [comment]
@mosabua System scoped not supported was my recollection too.
@tchoulihan where are your missing resources located?

**Comment by tchoulihan** [comment]
<systemPath>${basedir}/src/main/libs/CastCompanionLibrary-debug.aar</systemPath>

**Comment by william-ferguson-au** [comment]
OK, so since it is not being added because it is a system lib that would explain why they are not being found. 

Is there a reason you can't deploy the AAR to you local repo and reference as a standard dependency?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
