### ISSUE TITLE
[4.3.0] AAR with dummy classes disappeared

### ISSUE THREAD

**Issue by crossmo** [simpligility/android-maven-plugin#692]
Hi, I am trying to run Proguard on a project used an AAR dependency that are not well packaged. I can see a dummy classes.jar is created in the building process and shown in the input jar files for Proguard, 

The strange thing was that the classes.jar did not exist there so that Proguard however complained that file was missing.

```
		<dependency>
			<groupId>io.pristine</groupId>
			<artifactId>libjingle</artifactId>
			<version>10111</version>
			<type>aar</type>
		</dependency>
```

I checked the source code ProguardMojo.java seems work well, maybe the dummy classes.jar is cleaned somewhere before calling Proguard.

**Comment by bambooer** [comment]
I disabled Proguard and the error still existed there

```
org.apache.maven.plugin.MojoExecutionException: Error generating BuildConfig
	at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.isBuildConfigPresent(GenerateSourcesMojo.java:1206)
	at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.skipBuildConfigGeneration(GenerateSourcesMojo.java:1156)
	at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateBuildConfig(GenerateSourcesMojo.java:1137)
	at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:329)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.FileNotFoundException: /Users/tom/repo/mixed/core/android/target/unpacked-libs/ip_libjingle_10111/classes.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at com.simpligility.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.isBuildConfigPresent(GenerateSourcesMojo.java:1198)

```

In the meanwhile, the ```[DEBUG] Created dummy classes.jar exist=true``` was shown when running ```mvn clean install```

**Comment by crossmo** [comment]
I resolved this by running 
1) ```mvn eclipse:eclipse``` make the AAR unpackaged first
2) Refresh the project in Eclipse and get files compiled
3) ```mvn install``` without ```clean``` get things packaged without the missing classes.jar error

**Comment by william-ferguson-au** [comment]
What's the question or issue?

**Comment by crossmo** [comment]
```mvn clean install``` got failed with the error: 'xxx.classes.jar' is missing

**Comment by william-ferguson-au** [comment]
So what do you want us to do?
libjingle.aar is not a correctly package AAR

**Comment by crossmo** [comment]
OK, this does not concern your work.
