### ISSUE TITLE
Cannot add AARs to test morse app

### ISSUE THREAD

**Issue by ymenager** [simpligility/android-maven-plugin#694]
While trying to find the root cause for #693 , I've found something odd.

If I try to add appcompat-v7 to the test morse app (aar generated from https://github.com/simpligility/maven-android-sdk-deployer), the unit tests will fail with the error below.

```
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>appcompat-v7</artifactId>
      <version>23.0.0</version>
      <type>aar</type>
    </dependency>
```

I can fix that by making the dependency on the apk to be 'provided', but I'm suspecting having done so is what's causing #693 .....

```
[INFO] Convert classes to Dex : /Users/yannick/Projects/android-maven-plugin/src/test/projects/morseflash/morseflash-instrumentation/target/classes.dex
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$anim;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$attr;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$bool;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$color;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$dimen;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$drawable;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$id;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$integer;
[INFO] Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v7/appcompat/R$layout;
[INFO] 
[INFO] UNEXPECTED TOP-LEVEL EXCEPTION:
[INFO] java.lang.RuntimeException: Translation has been interrupted
[INFO] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[INFO] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[INFO] 	at com.android.dx.command.dexer.Main.run(Main.java:277)
[INFO] 	at com.android.dx.command.dexer.Main.main(Main.java:245)
[INFO] 	at com.android.dx.command.Main.main(Main.java:106)
[INFO] Caused by: java.lang.InterruptedException: Too many errors
[INFO] 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[INFO] 	... 4 more
```

**Comment by ymenager** [comment]
I tried with a recyclerview-v7 and some others aars and the same problem happens....

So either the example is wrong (and the dependency must be `provided` rather than compile.. in which case I hope that's not what would be causing #693), or there's something deeply broken in the plugin

**Comment by william-ferguson-au** [comment]
Two things
1) Make sure you are doing this from a clean build.
2) Why do you need the sdk-deployer to generate appcompat-v7? Isn't it shipped with the SDK maven repo?

I haven't looked at this in detail but generally speaking you should be including an AAR with scope of 'compile'. I wouldn't have expected 'provided'.

**Comment by mosabua** [comment]
Use the correct AAR. That should fix the issue. Just renaming a file from apk to aar does not change it into and aar.
