### ISSUE TITLE
Error building aar. Could not add classes.jar as dependency: ZIP file must have at least one entry -> [Help 1]

### ISSUE THREAD

**Issue by esedin** [simpligility/android-maven-plugin#714]
Error building Android aar module with Java 1.6.0_45.
I built aar-child project from android-maven-plugin examples.

[ERROR] Could not add classes.jar as dependency: ZIP file must have at least one entry -> [Help 1]
org.apache.maven.MavenExecutionException: Could not add classes.jar as dependency
        at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.addClassesToClasspath(ClasspathModifierLifecycleParticipant.java:299)
        at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.afterProjectsRead(ClasspathModifierLifecycleParticipant.java:171)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:271)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.zip.ZipException: ZIP file must have at least one entry
        at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:304)
        at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:140)
        at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:321)
        at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.addClassesToClasspath(ClasspathModifierLifecycleParticipant.java:294)
        ... 14 more

mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 18:22:22+0300)
Maven home: C:\Program Files\apache-maven-3.1.1
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: C:\Program Files (x86)\Java\jdk1.6.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

With Java 7+ everything OK.

Looks like issue with ZipOutputStream.finish() method

**Java 6**
```
public void finish() throws IOException {
        ...
        if (current != null) {
            closeEntry();
        }
        if (xentries.size() < 1) {
            throw new ZipException("ZIP file must have at least one entry");
        }
        ...
    }
```

**Java 7+** has no condition
```
...
        if (xentries.size() < 1) {
            throw new ZipException("ZIP file must have at least one entry");
        }
...
```

[aar-child.zip](https://github.com/simpligility/android-maven-plugin/files/119145/aar-child.zip)

**Comment by william-ferguson-au** [comment]
Solution: Use Java 7.

**Comment by esedin** [comment]
Then please fix plugin description
[](http://simpligility.github.io/android-maven-plugin/)

....
Required Setup
Android SDK r21.1 or later, latest is best supported
Java Development Kit **1.6 - 1.8** as supported by the Android SDK
...

Thanks.

**Comment by william-ferguson-au** [comment]
Done

**Comment by meletis** [comment]
I'm using 4.4.1 and Java 6 and there is no problem. So I guess the issue was fixed in newer releases.
