### ISSUE TITLE
classes.jar from AAR dependencies are not added to classpath

### ISSUE THREAD

**Issue by sviperll** [simpligility/android-maven-plugin#738]
I try to use support library. Everything works except I see no support classes in classpath.

I see unpacked `appcompat-v7` library in `target/unpacked-libs/cas_appcompat-v7_23.4.0`.
There is an `classes.jar` file (i. e. `target/unpacked-libs/cas_appcompat-v7_23.4.0/classes.jar`).
But `classes.jar` file is not unpacked anywhere. There is no activity in maven log indicating classes.jar processing. So compilation simply fails with

````
package android.suppport.v7.app does not exist
````

Here is my pom.xml

````xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.mobico.sviperll</groupId>
    <artifactId>sberpusher-android-client</artifactId>
    <version>0.2-SNAPSHOT</version>
    <packaging>apk</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
        <android.sdk.path>${env.ANDROID_HOME}</android.sdk.path>
    </properties>
    <repositories>
        <repository>
            <id>google-android-maven</id>
            <name>Maven repository created by Android SDK installer</name>
            <url>file://${android.sdk.path}/extras/android/m2repository</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>android</groupId>
            <artifactId>android</artifactId>
            <version>4.3.1_r3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.android.support</groupId>
            <artifactId>appcompat-v7</artifactId>
            <version>23.4.0</version>
            <type>aar</type>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.simpligility.maven.plugins</groupId>
                    <artifactId>android-maven-plugin</artifactId>
                    <version>4.4.3</version>
                    <extensions>true</extensions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>com.simpligility.maven.plugins</groupId>
                <artifactId>android-maven-plugin</artifactId>
                <configuration>
                    <sdk>
                        <path>${android.sdk.path}</path>
                        <platform>23</platform>
                    </sdk>

                    <!-- I've tried to add this option but it doesn't effect build -->
                    <!-- <includeLibsJarsFromAar>true</includeLibsJarsFromAar> -->
                   
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
````

**Comment by sviperll** [comment]
I've tried to add android-maven-plugin to `.mvn/extensions.xml` file, but now I get

````
$ mvn -X clean install
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_73, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-8-oracle-x64/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "4.6.0-1-amd64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.codehaus.plexus.util.xml.Xpp3Dom -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.codehaus.plexus.util.xml.Xpp3Dom
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.codehaus.plexus.util.xml.Xpp3Dom
	at com.simpligility.maven.plugins.android.common.PomConfigurationHelper.getMojoConfiguration(PomConfigurationHelper.java:48)
	at com.simpligility.maven.plugins.android.common.PomConfigurationHelper.getPluginConfigParameter(PomConfigurationHelper.java:25)
	at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.getMojoConfigurationParameter(ClasspathModifierLifecycleParticipant.java:212)
	at com.simpligility.maven.plugins.android.phase_prebuild.ClasspathModifierLifecycleParticipant.afterProjectsRead(ClasspathModifierLifecycleParticipant.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

````

**Comment by sviperll** [comment]
It's my fault. Everything works as advertised. I've just misstyped `support` in package name. So I'll close this.

The remaining problem is that NetBeans doesn't see classes extracted from AAR libraries... So I've manually add a dependecy for netbeans as a work-around. It doesn't affect build at all as android-maven-plugin adds the same dependecy, but it allows NetBeans to see this classes...

````xml
        <dependency>
            <groupId>com.android.support</groupId>
            <artifactId>appcompat-v7</artifactId>
            <version>23.4.0</version>
            <type>jar</type>
            <scope>system</scope>
            <systemPath>${project.build.directory}/unpacked-libs/cas_appcompat-v7_23.4.0/classes.jar</systemPath>
        </dependency>
````
