### ISSUE TITLE
fail to execute the emulator-start goal

### ISSUE THREAD

**Issue by hqfking** [simpligility/android-maven-plugin#739]
my machine is Win10
java is 1.7.0_79
maven is 3.1.1

when i try the command:  mvn android:emulator-start, I got the following error:

[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.3:emulator-start (default-cli) on project matlabmobile-test: MojoExecutionException: ANDROID-040-002: Could not execute: Command = cmd.exe /X /C "C:\Users\dhuang\AppData\Local\Temp\android-maven-plugin-emulator-start.vbs", Error message = Error while executing process. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.4.3:emulator-start (default-cli) on project matlabmobile-test:
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
        at com.simpligility.maven.plugins.android.AbstractEmulatorMojo.startAndroidEmulator(AbstractEmulatorMojo.java:264)
        at com.simpligility.maven.plugins.android.standalonemojos.EmulatorStartMojo.execute(EmulatorStartMojo.java:26)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

However, if I copy the command:
cmd.exe /X /C "C:\Users\dhuang\AppData\Local\Temp\android-maven-plugin-emulator-start.vbs"

and execute it in the same command window, it gets executed successfully. 

Not sure what I missed here.

**Comment by witekkij** [comment]
any luck resolving this?

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
