### ISSUE TITLE
ProguardMojo attempts to process classes contained in library META-INF folders

### ISSUE THREAD

**Issue by william-ferguson-au** [simpligility/android-maven-plugin#765]
In truth this is an error in Proguard (https://sourceforge.net/p/proguard/bugs/665/), but we could work around it by adding an exclusion filter for "META-INF/**/*.class" in the ProguardMojo.

To give context, this is the output generated when trying to Proguard against log4j2-2.9.0 which includes some JDK9 byte code classes in META-INF.

```
[INFO] --- android-maven-plugin:4.5.1-SNAPSHOT:proguard (default-proguard) @ Lexathon ---
[INFO] Proguarding output
[INFO] java.io.IOException: Can't read [E:\maven-local-repository\org\apache\logging\log4j\log4j-api\2.9.0\log4j-api-2.9.0.jar(;;;;;;!META-INF/maven/**,!META-INF/MANIFEST.MF)] (Can't process class [META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))
[INFO] 	at proguard.InputReader.readInput(InputReader.java:188)
[INFO] 	at proguard.InputReader.readInput(InputReader.java:158)
[INFO] 	at proguard.InputReader.readInput(InputReader.java:136)
[INFO] 	at proguard.InputReader.execute(InputReader.java:66)
[INFO] 	at proguard.ProGuard.readInput(ProGuard.java:218)
[INFO] 	at proguard.ProGuard.execute(ProGuard.java:82)
[INFO] 	at proguard.ProGuard.main(ProGuard.java:538)
[INFO] Caused by: java.io.IOException: Can't process class [META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8))
[INFO] 	at proguard.io.ClassReader.read(ClassReader.java:112)
[INFO] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[INFO] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[INFO] 	at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[INFO] 	at proguard.io.JarReader.read(JarReader.java:65)
[INFO] 	at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[INFO] 	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[INFO] 	at proguard.InputReader.readInput(InputReader.java:184)
[INFO] 	... 6 more
[INFO] Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [53.0] (maximum 52.0, Java 1.8)
[INFO] 	at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:145)
[INFO] 	at proguard.classfile.io.ProgramClassReader.visitProgramClass(ProgramClassReader.java:95)
[INFO] 	at proguard.classfile.ProgramClass.accept(ProgramClass.java:358)
[INFO] 	at proguard.io.ClassReader.read(ClassReader.java:91)
[INFO] 	... 13 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.338 s
[INFO] Finished at: 2017-09-13T04:34:23+10:00
[INFO] Final Memory: 33M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.5.1-SNAPSHOT:proguard (default-proguard) on project Lexathon: MojoExecutionException: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "E:\Dev\jdk1.8.0_74\jre\bin\java -Xmx512M -jar E:\maven-local-repository\net\sf\proguard\proguard-base\5.3.3\proguard-base-5.3.3.jar @E:\Source\lexathon\lexathon-game\target\proguard\temp_config.cfg", Result = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.5.1-SNAPSHOT:proguard (default-proguard) on project Lexathon: 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: 
	at com.simpligility.maven.plugins.android.phase04processclasses.ProguardMojo.executeProguard(ProguardMojo.java:503)
	at com.simpligility.maven.plugins.android.phase04processclasses.ProguardMojo.execute(ProguardMojo.java:400)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: com.simpligility.maven.plugins.android.ExecutionException: ANDROID-040-001: Could not execute: Command = cmd.exe /X /C "E:\Dev\jdk1.8.0_74\jre\bin\java -Xmx512M -jar E:\maven-local-repository\net\sf\proguard\proguard-base\5.3.3\proguard-base-5.3.3.jar @E:\Source\lexathon\lexathon-game\target\proguard\temp_config.cfg", Result = 1
	at com.simpligility.maven.plugins.android.CommandExecutor$Factory$DefaultCommandExecutor.executeCommand(CommandExecutor.java:249)
	at com.simpligility.maven.plugins.android.phase04processclasses.ProguardMojo.executeProguard(ProguardMojo.java:499)
	... 24 more
[ERROR] 

```

**Comment by mosabua** [comment]
Closing old issues as part of cleanup effort. Feel free to re-open and submit a PR with fix.
